#
####################################################################
#                     official CI/CD Settings                      #
####################################################################
#
#
stages:
  - code_build
  - code_quality
  - code_test

compile:
  stage: code_build
  extends:
    - .tags
  before_script:
    - geoapp snapshot --lock
    - geoapp install --link=false --cache=.npm -v
  script:
    - grunt exec:tsc
  cache:
    key: "$CI_PROJECT_NAME-$CI_JOB_STAGE"
    paths:
      - .npm/
  artifacts:
    paths:
      - ./
    exclude:
      - .git*
      - .git/
      - .npm/
    when: on_success
    expire_in: 15 min

eslint:
  extends:
    - .code_quality
  script:
    - grunt eslint

tslint:
  extends:
    - .code_quality
  script:
    - grunt tslint
  allow_failure: true

todo:
  extends:
    - .code_quality
  script:
    - grunt todo

jsdoc:
  extends:
    - .code_quality
  script:
    - grunt jsdoc

unit_tests_mocha:
  extends:
    - .code_test
  script:
    - grunt mochaTest
#
#
#
#
#
#
#
#
####################################################################
#             predefined properties for job-settings               #
####################################################################
#
.tags:
  tags:
    - GeoportalRunner # temporary for test gitlab system
    - debRunner # temporary for test gitlab system

.code_quality:
  extends:
    - .tags
  stage: code_quality
  needs: [ "compile" ]

.code_test:
  extends:
    - .tags
  stage: code_test
  dependencies:
    - compile
  needs: ["compile", "eslint", "todo", "jsdoc"]
  retry:
    max: 2
