include:
  - project: "Geosolution/gitlab-files"
    ref: master
    file: "/build/includes-files-tag.yml"

compile:
  stage: code_build
  extends:
    - .tags
  before_script:
    - geoapp snapshot --lock
    - geoapp install --link=false --cache=.npm -v
  script:
    - grunt exec:tsc
  cache:
    key: "$CI_PROJECT_NAME-$CI_JOB_STAGE"
    paths:
      - .npm/
  artifacts:
    paths:
      - ./
    exclude:
      - .git*
      - .git/
      - .npm/
    when: on_success
    expire_in: 15 min

eslint:
  extends:
    - .code_quality
  script:
    - grunt eslint

tslint:
  extends:
    - .code_quality
  script:
    - grunt tslint
  allow_failure: true # @todo remove it when tslint is fixed
  retry: # @todo remove it when tslint is fixed
    max: 0 # @todo remove it when tslint is fixed

todo:
  extends:
    - .code_quality
  script:
    - grunt todo

jsdoc:
  extends:
    - .code_quality
  script:
    - grunt jsdoc

unit_tests_mocha:
  extends:
    - .code_test
  script:
    - grunt mochaTest
#
# supplements of the import templates
.code_test:
  needs: [ "compile", "eslint", "todo", "jsdoc" ] # , "tslint" @todo include when tslint is fixed
