include:
  - project: "geosolutions/gitlab-files"
    ref: master
    file: "/build/includes-files-tag.yml"

compile:
  extends:
    - .code_build
  before_script:
    - geoapp snapshot --lock
    - geoapp install --link=false --cache=.npm -v
  script:
    - grunt exec:tsc

eslint:
  extends:
    - .code_quality
  script:
    - grunt eslint

tslint:
  extends:
    - .code_quality
  script:
    - grunt tslint
  allow_failure: true # @todo remove it when tslint is fixed
  retry: # @todo remove it when tslint is fixed
    max: 0 # @todo remove it when tslint is fixed

todo:
  extends:
    - .code_quality
  script:
    - grunt todo

jsdoc:
  extends:
    - .code_quality
  script:
    - grunt jsdoc

unit_tests_mocha:
  extends:
    - .code_test
  script:
    - grunt mochaTest
#
# supplements of the import templates
.code_test:
  needs: [ "compile", "eslint", "todo", "jsdoc" ] # , "tslint" @todo include when tslint is fixed
