module.exports = {
    env: {
        browser: true,
        es6: true,
        node: true,
        mocha: true
    },
    extends: "tslint:recommended",
    rules: {
        "max-line-length": {
            options: [150]
        },
        "member-access": false,
        "no-any": false,
        "callable-types": false,
        "no-empty-interface": false,
        "prefer-for-of": true,
        "promise-function-async": true,
        "ban-comma-operator": true,
        "function-constructor": true,
        "no-invalid-this": true,
        "member-ordering": false,
        "max-classes-per-file": [true, 1],
        "prefer-readonly": true,
        "only-arrow-function": "allow-named-functions",
        "trailing-comma": [true, { multiline: "never", singleline: "never" }],
        "object-literal-sort-keys": false,
        "object-literal-shorthand": false,
        align: [true, "members", "statements"],
        "variable-name": false,
        "no-shadowed-variable": false,
        "ordered-imports": false,
        "interface-name": false,
        curly: true,
        "arrow-parens": true,
        encoding: true,
        "arrow-return-shorthand": true,
        complexity: [true, 5],
        "no-debugger": true,
        semicolon: true,
        "no-bitwise": true,
        "no-conditional-assignment": true,
        "triple-equals": true,
        "no-eval": true,
        "no-unused-expression": true,
        "no-consecutive-blank-lines": [true, 2],
        forin: true,
        "no-use-before-declare": false,
        "no-arg": true,
        "no-construct": true,
        "no-empty": true,
        indent: [true, "spaces", 4],
        quotemark: [true, "double"],
        whitespace: true,
        "space-before-function-paren": [true, { anonymous: "always", named: "never", asyncArrow: "always" }],
        "no-trailing-whitespace": true,
        "no-irregular-whitespace": true,
        "one-line": true,
        "space-within-parens": [true, 0],
        "object-literal-key-quotes": [true, "as-needed"],
        eofline: true,
        "comment-format": [true, "check-space"],
        "no-return-await": true,
        "no-string-literal": true,
        "no-string-throw": true,
        radix: true,
        "only-arrow-functions": false,
        "prefer-method-signature": true
    },
    jsRules: true
};
